language: python

dist: xenial
sudo: true

python:
    - 3.6
    - 3.7

install:
    - pip install poetry
    - poetry install

script:
    - flake8 --version
    - flake8 graphql tests
    - black --version
    - black graphql tests --check
    - mypy --version
    - mypy graphql
    - pytest --version
    - pytest --cov-report term-missing --cov=graphql

after_success:
    - codecov
