[tool.poetry]
name = "graphql-core"
version = "17.0.0a0"
description = """
GraphQL-core is a Python port of GraphQL.js,\
 the JavaScript reference implementation for GraphQL."""
license = "MIT"
authors = [
    "Christoph Zwerschke <cito@online.de>"
]
readme = "README.md"
homepage = "https://github.com/graphql-python/graphql-core"
repository = "https://github.com/graphql-python/graphql-core"
documentation = "https://graphql-core-3.readthedocs.io/"
keywords = ["graphql"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10"
]
packages = [
    { include = "graphql", from = "src" },
    { include = "tests", format = "sdist" },
    { include = "docs", format = "sdist" },
    { include = '.bumpversion.cfg', format = "sdist" },
    { include = '.coveragerc', format = "sdist" },
    { include = '.editorconfig', format = "sdist" },
    { include = '.flake8', format = "sdist" },
    { include = '.mypy.ini', format = "sdist" },
    { include = '.readthedocs.yaml', format = "sdist" },
    { include = 'poetry.lock', format = "sdist" },
    { include = 'tox.ini', format = "sdist" },
    { include = 'setup.cfg', format = "sdist" },
    { include = 'CODEOWNERS', format = "sdist" },
    { include = 'MANIFEST.in', format = "sdist" },
    { include = 'SECURITY.md', format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.7"
typing-extensions = [
    { version = "^4.3", python = "<3.8" },
]

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pytest-asyncio = ">=0.19,<1"
pytest-benchmark = "^3.4"
pytest-cov = "^3.0"
pytest-describe = "^2.0"
pytest-timeout = "^2.1"
black = "22.8.0"
flake8 = "^5.0"
mypy = "0.971"
sphinx = "^5.1"
sphinx_rtd_theme = ">=1,<2"
check-manifest = ">=0.48,<1"
bump2version = ">=1.0,<2"
tox = "^3.26"

[tool.black]
target-version = ['py37', 'py38', 'py39', 'py310']

[build-system]
requires = ["poetry_core>=1,<2", "setuptools>=65,<70"]
build-backend = "poetry.core.masonry.api"
